---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: cephfs.csi.ceph.com
spec:
  attachRequired: true
  fsGroupPolicy: File
  podInfoOnMount: false
  seLinuxMount: true
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: nfs.csi.ceph.com
spec:
  attachRequired: false
  fsGroupPolicy: File
  seLinuxMount: true
  volumeLifecycleModes:
  - Persistent
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: rbd.csi.ceph.com
spec:
  attachRequired: true
  fsGroupPolicy: File
  podInfoOnMount: false
  seLinuxMount: true
