---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
- controllers.yaml
secretGenerator:
- name: mongodb-compass
  envs:
  - compass.env
  literals:
  - CW_ENABLE_EDIT_CONNECTIONS=false
