---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
  name: default
provisioner: kubernetes.io/host-path
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-cephfs
provisioner: cephfs.csi.ceph.com
parameters:
  clusterID: ed6d3982-f559-4d2d-a99e-de040380f967
  fsName: default
  pool: default.cephfs
  csi.storage.k8s.io/provisioner-secret-name: ceph-csi-cephfs
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/controller-expand-secret-name: ceph-csi-cephfs
  csi.storage.k8s.io/controller-expand-secret-namespace: kube-system
  csi.storage.k8s.io/controller-publish-secret-name: ceph-csi-cephfs
  csi.storage.k8s.io/controller-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: ceph-csi-cephfs
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
allowVolumeExpansion: true
reclaimPolicy: Delete
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-cephfs-tmp
provisioner: cephfs.csi.ceph.com
parameters:
  clusterID: ed6d3982-f559-4d2d-a99e-de040380f967
  fsName: tmp
  pool: tmp.cephfs
  csi.storage.k8s.io/provisioner-secret-name: ceph-csi-cephfs-tmp
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/controller-expand-secret-name: ceph-csi-cephfs-tmp
  csi.storage.k8s.io/controller-expand-secret-namespace: kube-system
  csi.storage.k8s.io/controller-publish-secret-name: ceph-csi-cephfs-tmp
  csi.storage.k8s.io/controller-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: ceph-csi-cephfs-tmp
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
allowVolumeExpansion: true
reclaimPolicy: Delete
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-rbd
provisioner: rbd.csi.ceph.com
parameters:
  clusterID: ed6d3982-f559-4d2d-a99e-de040380f967
  pool: default.rbd
  imageFeatures: layering
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/provisioner-secret-name: ceph-csi-rbd
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/controller-expand-secret-name: ceph-csi-rbd
  csi.storage.k8s.io/controller-expand-secret-namespace: kube-system
  csi.storage.k8s.io/controller-publish-secret-name: ceph-csi-rbd
  csi.storage.k8s.io/controller-publish-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: ceph-csi-rbd
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
allowVolumeExpansion: true
mountOptions:
- discard
reclaimPolicy: Delete
