---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- name: gloomhaven
  files:
  - application.properties=application.properties
  - server.json=server.json
resources:
- controllers.yaml
secretGenerator:
- name: gloomhaven
  literals:
  - DB_PASSWORD=password
  - DB_URL=postgresql://postgresql.default.svc.cluster.local:5432/gloomhaven
  - DB_USERNAME=default
